easy_admin:
  site_name:
      'Administration'
  entities:
      Reportage:
          class: App\Entity\Reportage
          list:
              fields:
                  - { property: 'title', type: 'string', label: 'Titre' }
                  - { property: 'createdAt', format: 'd/m/Y', label: 'Date' }
                  - { property: 'category', label: 'Catégorie' }
          edit:
              title: "modifications article"
              fields:
                  - { property: 'title', label: 'Titre' }
                  - { property: 'content', label: 'Contenu' }
                  - { property: 'imageFile', type: 'vich_image', label: 'Image principale', type_options: { required: false } }
                  - { property: 'carouselFile1', type: 'vich_image', label: 'Image carousel 1', type_options: { required: false } }
                  - { property: 'carouselFile2', type: 'vich_image', label: 'Image carousel 2', type_options: { required: false } }
                  - { property: 'carouselFile3', type: 'vich_image', label: 'Image carousel 3', type_options: { required: false } }
                  - { property: 'createdAt', label: 'Date de création' }
                  - { property: 'category', label: 'Catégorie' }                 
          new:
              title: "création article"
              fields:
                  - { property: 'title', label: 'Titre' }
                  - { property: 'content', label: 'Contenu' }
                  - { property: 'imageFile', type: 'vich_image', label: 'Image principale', type_options: { required: true } }
                  - { property: 'carouselFile1', type: 'vich_image', label: 'Image carousel 1', type_options: { required: true } }
                  - { property: 'carouselFile2', type: 'vich_image', label: 'Image carousel 2', type_options: { required: true } }
                  - { property: 'carouselFile3', type: 'vich_image', label: 'Image carousel 3', type_options: { required: true } }
                  - { property: 'createdAt', label: 'Date de création' }
                  - { property: 'category', label: 'Catégorie' }
      Category:
          class: App\Entity\Category
          list:
              actions:
                  - { name: 'new', label: 'Créer Catégorie' }
              fields:
                  - { property: 'name', label: 'Nom'}
                  - reportages
          form:
              fields:
                  - { property: 'name', label: 'Nom' }
      User:
          class: App\Entity\User
          list:
              fields:
                  - { property: 'username', label: 'Nom'}
                  - { property: 'email' }
          form:
              fields:
                  - { property: 'username', label: 'Nom' }
                  - { property: 'email' }
          disabled_actions: ['new', 'delete']          
  design:
        brand_color: '#2C3E50'
        menu:
          - { label: 'Accueil', route: 'home' }
          - { entity: 'Reportage', label: 'Reportages' }
          - { entity: 'Category', label: 'Catégories' }
          - { entity: 'User', label: 'Utilisateur' }
          - { label: 'Déconnexion', route: 'security_logout' }