vich_uploader:
    db_driver: orm

    mappings:
        reportage_image:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images/'
            delete_on_update: true
            delete_on_remove: true
